# Generated by Django 4.0.3 on 2022-12-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='Courses_name',
            new_name='courses_name',
        ),
    ]
